### ISSUE TITLE
Liar a la gente y birras pagadas

### ISSUE THREAD

**Issue by UlisesGascon** [memezinga/memezinga-legacy#10]
### Pendiente
- [ ] Liar a la gente en twitter (TODOS). Especialmente @CodingCarlos y @baumannzone
- [ ] Medir los retuits con un script con un hashtag basado en el nombre (ver con ulises)

**Comment by UlisesGascon** [comment]
Elena y Vicky

**Comment by baumannzone** [comment]
¿Yo que pinto aquí? ¡Exijo un resumen!

**Comment by Sediug** [comment]
Tú pagas las birras :beers:  ¿Votos a favor?

**Comment by Vickysolo** [comment]
@CodingCarlos, @baumannzone ya tenemos hecho el contador, pero no vemos moviemiento de tweets ejem ejem...

**Comment by UlisesGascon** [comment]
Podeis pedir ayuda en el canal random y general de osw ;-)

Seguro que es facil liar a la gente! :-P

**Comment by UlisesGascon** [comment]
último recuento....  **78**
