### ISSUE TITLE
NORMAS para contribuir

### ISSUE THREAD

**Issue by UlisesGascon** [memezinga/memezinga-legacy#12]
- Será un proyecto colaborativo gestionado por el Guild24
- Las contribuciones serán por PR. Solo @ulisesGascon aprobara los merges
- Se trabaja sobre la rama DEV o FEATURE-{{X}}
- Al menos otra persona del equipo deberá revisar y comentar tu PR. Ver #3 
- Será necesario mantener un standard... 
    - [Documentación con JSDocs](http://www.boyter.org/wp-content/uploads/2016/08/CgGkN6YVAAAZ3_1.jpg)
    - [JS Linter](https://jaredforsyth.com/type-systems-js-dev/images/not_work.jpg)
    - [commits](https://pbs.twimg.com/media/CgbR1wkXEAAMjqP.jpg)
    - [Sin frameworks ni librerias](https://i.imgur.com/qPmLthz.jpg)
    - [Leer la documentación](https://i.imgur.com/v8hVVdF.jpg)
    - [Refactorizaciones frecuntes](https://i.imgur.com/IQBhKkT.jpg)
    - [Nombres de variables, comentarios y demás será en ingles](https://calidadysoftware.files.wordpress.com/2015/07/c3b1apa-as-a-service.png)

**Comment by Sediug** [comment]
Ñapa as a Service 10/10 haha
