### ISSUE TITLE
Marca de agua 

### ISSUE THREAD

**Issue by UlisesGascon** [memezinga/memezinga-legacy#67]
Meter una marca de agua al meme que se genera
`Generado con #Memezinga` (Lateral Derecha con padding )

**Comment by UlisesGascon** [comment]
**Recursos
-  https://stackoverflow.com/questions/40939662/node-gm-watermark-and-resize
- http://aheckmann.github.io/gm/docs.html

**Comment by ElenaMLopez** [comment]
https://www.npmjs.com/package/dynamic-watermark
A ver que os parece esto =)

**Comment by UlisesGascon** [comment]
Aqui un ejemplo de memegenerator.com
![pretty-please](https://user-images.githubusercontent.com/5110813/37507685-217d8f9c-28f0-11e8-9731-a6e2ffa996a8.jpg)

**Comment by ValKiriann** [comment]
vaia vaia justo donde os dijo mamá que había que ponerla....
